### ISSUE TITLE
Campus Map Projects

### ISSUE THREAD

**Issue by WilliamChittester** [pennstategeog467/fall-2015#2]
**OpenStreetMap Editing**
- Sidewalks "May require field work 
- Athletic & IM fields
- Downtown Buisnesses

**PSU Data**
- Trees
- Implement Building heights
  - Transform roof details to match relative to top of building
  - Heights could just be relative to the overall height
  - Roof-line file is not specific to each building

**Online Map**
- Directions
  - Add a starting place option
  - Options for driving/bicycle/walking
- Live Cata Bus Locations/Routes
- Parking
  - Everyday student/staff/visitor parking
  - Event specific parking ie. Football
- Transition between Day&Night Map
  - By click of button or time of day
  - Update night map styles to match the day map
- Bicycle Information
  - Racks/ServiceStations/Shops
- Penn State Branding

**Comment by aaronpdennis** [comment]
hey @WilliamChittester I made a pull request with just an idea if you want to merge that into the repository's main README.md and add this information too

**Comment by WilliamChittester** [comment]
Will do.

**Comment by WilliamChittester** [comment]
@aaronpdennis I updated the readme, and I included Pop-Carte, since Cindy was talking about doing that again.  Also I've been working on a few conceptual ideas, on how to creating a site similar to geojson.io but focused specifically on the editing our our map.
